### ISSUE TITLE
How to test QML Components?

### ISSUE THREAD

**Issue by Siecje** [pytest-dev/pytest-qt#125]
I'm wondering how you would test a QML application. Here is how I am creating my QML application. What should I call on qtbot?

```Python
class UsersManager(QtCore.QObject):
    users = QtCore.pyqtSignal(QtCore.QVariant)
    
    @QtCore.pyqtSlot()
    def LoadUsers(self):
        def thread():
            users = FetchUsers()
            self.users.emit(users)
            
        threading.Thread(target=thread).start()

app = QtGui.QGuiApplication(sys.argv)
QtQml.qmlRegisterType(UsersManager, 'UsersManager', 1, 0, 'UsersManager')
engine = QtQml.QQmlApplicationEngine("Main.qml")
app.exec_()
```

**Comment by nicoddemus** [comment]
TBH I never used QML so I'm not sure. The [documentation](http://doc.qt.io/qt-5/qtquick-qtquicktest.html) for testing QML applications suggests that it needs its own runner because the tests are written in JS, so perhaps the only possible integration with py.test is running the tests as a "black box", similar to what's done with [pytest-cpp](github.com/pytest-dev/pytest-cpp).

**Comment by The-Compiler** [comment]
Should we close this?

**Comment by nicoddemus** [comment]
I'm closing this for now.
