### ISSUE TITLE
Unable to test drag and drop

### ISSUE THREAD

**Issue by 90ender** [pytest-dev/pytest-qt#260]
I have noticed that using qtbot mouse signals fails to trigger drag events. While mouse press and release are detected, mouse move doesn't trigger the drag action. Here is my example code.

Note: I am using a qt compatibility module, so you will need to fix the qt imports at the top to match your setup.

[https://pastebin.com/tphMypVF](url)

**Comment by nicoddemus** [comment]
Hi @90ender,

Not sure how to test drag and drop using mouse events; if it is not working, perhaps you can try to send `dragEnterEvent` and `dropEvent` directly to the widget under testing? See [this example](https://doc.qt.io/qt-5/qtwidgets-draganddrop-draggabletext-dragwidget-cpp.html) for guidance.

`qtbot` calls [`QTest`](https://doc.qt.io/qt-5/qtest.html) methods under the covers, so if you can test drag and drop events using `QTest` methods you should be able to test it using `qtbot`. I'm mentioning this because you might try to post your question using `QTest` to Qt groups and/or SO; anything that works there should be translatable to `qtbot`.

**Comment by 90ender** [comment]
Looking into it further, it does seem that this is currently a bug with QTest.

**Comment by nicoddemus** [comment]
@90ender thanks for the follow up. Should we close this then given that there's no action point for `pytest-qt`?
