### ISSUE TITLE
`waitSignal` returns immediately although signal not emitted

### ISSUE THREAD

**Issue by bersbersbers** [pytest-dev/pytest-qt#486]
If I am not mistaken, this test should wait forever for the signal to be emitted. Instead, it passes immediately.

```python
from PySide6.QtCore import QObject, Signal

class Signaller(QObject):
    signal = Signal()

def test_should_fail_but_passes(qtbot):
    signaller = Signaller()
    qtbot.waitSignal(signaller.signal)
```

pytest==7.3.1
pytest-qt==4.2.0
PySide6-Essentials==6.5.0

**Comment by nicoddemus** [comment]
Hi,

`waitSignal` should be used as a context manager, see: https://pytest-qt.readthedocs.io/en/latest/signals.html

**Comment by The-Compiler** [comment]
I see no reason either why the fixed version of the code wouldn't work, for what it's worth. It's pretty much the most simple (correct) usage, and pretty much what the pytest-qt testsuite tests too.

**Comment by nicoddemus** [comment]
For example:

```python
from PySide6.QtCore import QObject, Signal

class Signaller(QObject):
    signal = Signal()

def test_should_fail_but_passes(qtbot):
    signaller = Signaller()
    with qtbot.waitSignal(signaller.signal):
        signaller.signal.emit()
```

```
λ pytest .tmp\test_signal.py --no-header
======================== test session starts ========================
collected 1 item

.tmp\test_signal.py .                                          [100%]

========================= 1 passed in 0.02s =========================

```

**Comment by nicoddemus** [comment]
Hi @bersbersbers,

Thanks for all the input.

> https://pytest-qt.readthedocs.io/en/latest/signals.html says that qtbot.assertNotEmitted is a context manager. It does not say that in the text for waitSignal, and that would be great.

Agreed, a PR would be welcome.

> Yes, all code examples do use a context manager, but every other Python context manager that I know...

I agree with your point about the naming, we probably could have used a name which indicates that it is a context manager, perhaps something like `waitingSignal`, which reads nicely as a context manager: `with waitingSignal(...)`.

But I must disagree about this being a strange way to use a context manager, as I can think of a few examples:

[asyncio TaskGroups](https://docs.python.org/3/library/asyncio-task.html#task-groups) where the `TaskGroup` context-manager is used to spawn tasks inside the body, and wait for them to finish on `__exit__`.

[trio Nursery](https://trio.readthedocs.io/en/stable/reference-core.html#the-nursery-api) follows the same idea as above.

I'm sure there are others examples of asynchronous events being triggered inside a `with` block, and automatically waited on `__exit__`.

> Finally, I must admit I had not read https://pytest-qt.readthedocs.io/en/latest/reference.html#pytestqt.qtbot.QtBot.waitSignal. The information there looks very good and complete.


Thanks.

In the future however, when using a new library and things do not work as you expect initially, I suggest you to read the docs first, before asking for help from others. I believe this is considered polite, because it shows one has done its "homework" before asking for help. If you think the docs are good but the API is confusing, then all by means go ahead and provide feedback, which is always welcome. I feel this flow is more productive for everyone involved.

---

About the examples you posted, they are all valid actually. However, it is strongly recommended to write the code that triggers the signal *inside* the context manager, as at that point, the machinery to capture the signal has been setup. If you are using QueuedConnections for the signal, then triggering it before the the context manager will probably work, because the signal will be evaluated on the next pass through the event loop, at which point the signal will be captured.

As I mentioned before, using context managers to handle asynchronous events is quite common, I think.


---

> Conditional context managers are a pain in python, involving the use of nullcontext() or the like. So for conditional waits, the context-manager notation is very inconvenient.

I agree about conditional context managers being a pain, but we do have the `wait` API in case you want to avoid or cannot use the context manager.

> Finally (I promise), another source for confusion is that as an instruction, qtbot.wait() waits while qtbot.waitSignal() does not. I think that is the main reason why I ever fell for this issue.

Yes, you are definitely right this is confusing.

If I were starting now, I would write the API differently:

``` python
signaller = Signaller()
with qtbot.waitingSignal(signaller.signal):
    signaller.signal.emit()

# or:

signaller = Signaller()
blocker = qtbot.SignalBlocker(signaller.signal)  # connects using QueuedConnection
signaller.signal.emit()
blocker.wait()
```

However I'm not sure it is worth changing the API at this point.

Closing this then, again thanks for the feedback, and feel free to open a PR with improvements to the docs that you feel would help new users do not fall into the same traps. :+1:
