### ISSUE TITLE
Processing test events happens in hookwrapper

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#67]
So I was looking into why the exception in #65  is actually happening for me: It seems the test finishes *after* a module I'm monkeypatching is already un-monkeypatched:

```python
@pytest.fixture(autouse=True)
def mock_modules(monkeypatch, stubs):
    monkeypatch.setattr('qutebrowser.misc.guiprocess.message',
                        stubs.MessageModule())
```

I'm guessing this is because `pytest_runtest_teardown()` is decorated with `@pytest.mark.hookwrapper` - should it really be? I think it'd make more sense to run it before other fixtures are torn down.

**Comment by nicoddemus** [comment]
Hmm, the problem is not the hookwrapper *per-se*, I think the problem is that currently `processEvents()` is being called *after* all fixtures are torn down (after the `yield` statement):

```python
@pytest.mark.hookwrapper
def pytest_runtest_teardown(item):
    """
    Hook called after each test tear down, to process any pending events and
    avoiding leaking events to the next test.
    """
    yield
    app = QApplication.instance()
    if app is not None:
        if _exception_capture_disabled(item):
            app.processEvents()
        else:
            with capture_exceptions() as exceptions:
                app.processEvents()
            if exceptions:
                pytest.fail('TEARDOWN ERROR: ' + format_captured_exceptions(exceptions))
```

Just moving the `yield` statement would make the code run before all other fixture are tear down, which I think makes sense:

```python
@pytest.mark.hookwrapper
def pytest_runtest_teardown(item):
    """
    Hook called after each test tear down, to process any pending events and
    avoiding leaking events to the next test.
    """
    app = QApplication.instance()
    if app is not None:
        if _exception_capture_disabled(item):
            app.processEvents()
        else:
            with capture_exceptions() as exceptions:
                app.processEvents()
            if exceptions:
                pytest.fail('TEARDOWN ERROR: ' + format_captured_exceptions(exceptions))
    yield
```

I will think about this a little more, but meanwhile feel free to add any comments or insights! :smile:

**Comment by The-Compiler** [comment]
That seems to solve my issue, and all other tests still run fine for me.

I don't know what other implication that change would have, but I agree it sounds like it makes sense.

**Comment by nicoddemus** [comment]
I think actually we should process events both *before* and *after* the other tear down hooks, actually. Something like:

```python
def _process_events(item):
    app = QApplication.instance()
    if app is not None:
        if _exception_capture_disabled(item):
            app.processEvents()
        else:
            with capture_exceptions() as exceptions:
                app.processEvents()
            if exceptions:
                pytest.fail('TEARDOWN ERROR: ' + format_captured_exceptions(exceptions))

@pytest.mark.hookwrapper
def pytest_runtest_teardown(item):
    """
    Hook called after each test tear down, to process any pending events and
    avoiding leaking events to the next test.
    """
    _process_events(item)
    yield
    _process_events(item)
```

This will allow queued events to be processed in a more predicable manner. What do you think?

**Comment by The-Compiler** [comment]
Could any new events even arrive during the teardown? But yeah - why not!

**Comment by nicoddemus** [comment]
Actually any call to `app.processEvents()` may trigger any arbitrary code, which in turn might post other events, and so on... this is specially problematic in X-Window because the events are asynchronous, so a `processEvents()` may end up not processing any events at all. :worried: 

Calling `processEvents()` before and after other fixtures is only a best-effort to getting all events processed.
